# from
# https://github.com/do-community/example-doctl-action/blob/master/.github/workflows/workflow.yaml

on: push
jobs:
  test:
    name: Test and try publishing Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Install package
        run: flit install

      - name: run tests
        run: pytest record_api/test.py
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: true
      - name: Try publishing to PyPi
        run: flit publish
        continue-on-error: true
        env: 
          FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  build:
    needs: test
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Must upgrade to 1.6 which isn't available by default on ubuntu
      # https://stedolan.github.io/jq/download/
      - name: Create bin dir
        run: |
          mkdir -p bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Install new jq version
        run: |
          curl https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -L -o $GITHUB_WORKSPACE/bin/jq

      - name: Install argo
        run: |
          curl https://github.com/argoproj/argo/releases/download/v2.9.3/argo-linux-amd64 -L -o $GITHUB_WORKSPACE/bin/argo
      - name: Make bin executable
        run: chmod +x $GITHUB_WORKSPACE/bin/*
      - name: Verify argo
        run: argo 
      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Install package
        run: flit install

      - name: Clone buildx
        uses: actions/checkout@master
        with:
          repository: docker/buildx
          path: buildx
          ref: fd6de6b6aeac780c59e5079a96b068076b676d73

      - name: Install buildx
        working-directory: ./buildx
        run: make install

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # https://github.com/actions/starter-workflows/blob/master/ci/docker-publish.yml#L54
      - name: Log into docker registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save python-record-api

      - name: Create buildx driver
        working-directory: ./k8
        run: make buildx-driver

      - name: Push images
        working-directory: ./k8
        run: make push-images

      - name: Submit argo jobs
        working-directory: ./k8
        run: make argo-submit
      
      - name: list argo jobs
        run: argo list
